import { Routes } from '@angular/router';
import { Documentation } from './documentation/documentation';
import { BancoComponent } from './financeiro/components/banco/banco.component';
import { Crud } from './crud/crud';
import { Empty } from './empty/empty';
import { BolsaComponent } from './financeiro/components/bolsa/bolsa.component';
import { GrupoContaComponent } from './financeiro/components/grupoconta/grupoconta.component';
import { ContaComponent } from './financeiro/components/conta/conta.component';
import { SubcontaComponent } from './financeiro/components/subconta/subconta.component';
import { TipoDocumentoComponent } from './financeiro/components/tipodocumento/tipodocumento.component';
import { TipoCursoComponent } from './cursos/components/tipocurso/tipocurso.component';
import { ModalidadeComponent } from './cursos/components/modalidade/modalidade.component';
import { DisciplinaComponent } from './cursos/components/disciplina/disciplina.component';
import { MatrizCurricularComponent } from './cursos/components/matrizcurricular/matrizcurricular.component';
import { MovimentoComponent } from './financeiro/components/movimento/movimento.component';
import { SituacaoTurmaComponent } from './turmas/components/situacaoturma.component';
import { TurnoComponent } from './turmas/components/turnos.component';
import { SalaComponent } from './turmas/components/sala.component';
import { CargoComponent } from './funcionarios/components/cargo.component';
import { SituacaoContratoComponent } from './contratos/components/situacaocontrato.component';
import { TipoContratoComponent } from './contratos/components/tipocontrato.component';
import { CursoComponent } from './cursos/components/curso/curso.component';
import { FuncionarioComponent } from './funcionarios/components/funcionario.component';
import { TurmaComponent } from './turmas/components/turma.component';
import { ContratoComponent } from './contratos/components/contrato.component';
import { AlunoComponent } from './funcionarios/components/aluno.component';
import { TransfAlunoComponent } from './turmas/components/transfalunos.component';
import { FluxoCaixaComponent } from './financeiro/components/fluxocaixa/fluxocaixa.component';
import { FaixaDREComponent } from './financeiro/components/faixadre/faixadre.component';

export default [
    { path: 'documentation', component: Documentation },
    { path: 'movimentos', component: MovimentoComponent },
    { path: 'bancos', component: BancoComponent },
    { path: 'bolsas', component: BolsaComponent },
    { path: 'grupos_contas', component: GrupoContaComponent },
    { path: 'contas', component: ContaComponent },
    { path: 'subcontas', component: SubcontaComponent },
    { path: 'tipos_documentos', component: TipoDocumentoComponent },
    { path: 'tipos_cursos', component: TipoCursoComponent },
    { path: 'modalidades', component: ModalidadeComponent },
    { path: 'disciplinas', component: DisciplinaComponent },
    { path: 'matrizes_curriculares', component: MatrizCurricularComponent },
    { path: 'situacoes_turmas', component: SituacaoTurmaComponent },
    { path: 'turnos', component: TurnoComponent },
    { path: 'salas', component: SalaComponent },
    { path: 'cargos', component: CargoComponent },
    { path: 'situacoes_contratos', component: SituacaoContratoComponent },
    { path: 'contratos', component: ContratoComponent },
    { path: 'tipos_contratos', component: TipoContratoComponent },
    { path: 'funcionarios', component: FuncionarioComponent },
    { path: 'cursos', component: CursoComponent },
    { path: 'alunos', component: AlunoComponent },
    { path: 'transferencia_alunos', component: TransfAlunoComponent },
    { path: 'turmas', component: TurmaComponent },
    { path: 'fluxo_caixa', component: FluxoCaixaComponent },
    { path: 'dre', component: FaixaDREComponent },
    { path: 'crud', component: Crud },
    { path: 'empty', component: Empty },
    { path: '**', redirectTo: '/notfound' }
] as Routes;
