import { Routes } from '@angular/router';
import { Documentation } from './documentation/documentation';
import { BancoComponent } from './financeiro/components/banco.component';
import { Crud } from './crud/crud';
import { Empty } from './empty/empty';
import { BolsaComponent } from './financeiro/components/bolsa.component';
import { GrupoContaComponent } from './financeiro/components/grupoconta.component';
import { ContaComponent } from './financeiro/components/conta.component';
import { SubcontaComponent } from './financeiro/components/subconta.component';
import { TipoDocumentoComponent } from './financeiro/components/tipodocumento.component';
import { TipoCursoComponent } from './cursos/components/tipocurso.component';
import { ModalidadeComponent } from './cursos/components/modalidade.component';
import { DisciplinaComponent } from './cursos/components/disciplina.component';
import { TagComponent } from './financeiro/components/tag.component';
import { MatrizCurricularComponent } from './cursos/components/matrizcurricular.component';
import { MovimentoComponent } from './financeiro/components/movimento.component';
import { SituacaoTurmaComponent } from './turmas/components/situacaoturma.component';
import { TurnoComponent } from './turmas/components/turnos.component';
import { SalaComponent } from './turmas/components/sala.component';
import { CargoComponent } from './funcionarios/components/cargo.component';
import { SituacaoContratoComponent } from './contratos/components/situacaocontrato.component';
import { TipoContratoComponent } from './contratos/components/tipocontrato.component';
import { CursoComponent } from './cursos/components/curso.component';
import { FuncionarioComponent } from './funcionarios/components/funcionario.component';
import { TurmaComponent } from './turmas/components/turma.component';
import { ContratoComponent } from './contratos/components/contrato.component';
import { AlunoComponent } from './funcionarios/components/aluno.component';

export default [
    { path: 'documentation', component: Documentation },
    { path: 'movimentos', component: MovimentoComponent },
    { path: 'bancos', component: BancoComponent },
    { path: 'bolsas', component: BolsaComponent },
    { path: 'grupos_contas', component: GrupoContaComponent },
    { path: 'contas', component: ContaComponent },
    { path: 'subcontas', component: SubcontaComponent },
    { path: 'tags', component: TagComponent },
    { path: 'tipos_documentos', component: TipoDocumentoComponent },
    { path: 'tipos_cursos', component: TipoCursoComponent },
    { path: 'modalidades', component: ModalidadeComponent },
    { path: 'disciplinas', component: DisciplinaComponent },
    { path: 'matrizes_curriculares', component: MatrizCurricularComponent },
    { path: 'situacoes_turmas', component: SituacaoTurmaComponent },
    { path: 'turnos', component: TurnoComponent },
    { path: 'salas', component: SalaComponent },
    { path: 'cargos', component: CargoComponent },
    { path: 'situacoes_contratos', component: SituacaoContratoComponent },
    { path: 'contratos', component: ContratoComponent },
    { path: 'tipos_contratos', component: TipoContratoComponent },
    { path: 'funcionarios', component: FuncionarioComponent },
    { path: 'cursos', component: CursoComponent },
    { path: 'alunos', component: AlunoComponent },
    { path: 'turmas', component: TurmaComponent },
    { path: 'crud', component: Crud },
    { path: 'empty', component: Empty },
    { path: '**', redirectTo: '/notfound' }
] as Routes;
